# Generated by Django 5.1 on 2024-08-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.upload'),
        ),
        migrations.AddField(
            model_name='upload',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
