# Generated by Django 5.1 on 2024-08-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_upload_payment_payment_upload_upload_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uploaded_videos_count',
            new_name='trial_uploaded_videos_count',
        ),
    ]
