# Generated by Django 5.1 on 2024-09-03 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_upload_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='unique_session_id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='upload',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
    ]
