# Generated by Django 5.1 on 2024-09-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_unique_session_id_payment_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
