# Generated by Django 5.1 on 2024-09-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_payment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='args',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='upload',
            name='method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='upload',
            name='processed_video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='processed/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(max_length=500, upload_to='uploads/'),
        ),
    ]
