# Generated by Django 5.1 on 2024-09-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_upload_args_upload_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='video',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='processed_video',
            new_name='processed_file',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='trial_uploaded_videos_count',
            new_name='trial_uploaded_files_count',
        ),
    ]
